# Generated by Django 4.2.3 on 2023-07-27 17:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(default="member", max_length=10)),
                (
                    "startDate",
                    models.DateField(
                        default=datetime.date(2023, 7, 27), verbose_name="Start date"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        db_constraint=False,
                        default="Unassigned",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="teams.team",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
