# Generated by Django 4.2.3 on 2023-07-28 08:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
        ("usersinfo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="startDate",
            field=models.DateField(
                default=datetime.date(2023, 7, 28), verbose_name="Start date"
            ),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="team",
            field=models.ForeignKey(
                db_constraint=False,
                default=0,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="teams.team",
            ),
        ),
    ]
