# Generated by Django 4.2.3 on 2023-07-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usersinfo", "0002_alter_userinfo_startdate_alter_userinfo_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="role",
            field=models.CharField(
                choices=[
                    ("member", "member"),
                    ("team lead", "team lead"),
                    ("admin", "admin"),
                ],
                default="member",
                max_length=10,
            ),
        ),
    ]
