# Generated by Django 4.2.3 on 2023-07-28 13:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("usersinfo", "0003_alter_userinfo_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="startDate",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Start date"
            ),
        ),
    ]
